
# This file is automatically generated, you probably don't want to edit this

varsplitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "varsplitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            separator = "comma", ...) {

            super$initialize(
                package="SplitColumn",
                name="varsplit",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..separator <- jmvcore::OptionList$new(
                "separator",
                separator,
                options=list(
                    "comma",
                    "semicolon"),
                default="comma")
            private$..factorScoresOV <- jmvcore::OptionOutput$new(
                "factorScoresOV")

            self$.addOption(private$..dep)
            self$.addOption(private$..separator)
            self$.addOption(private$..factorScoresOV)
        }),
    active = list(
        dep = function() private$..dep$value,
        separator = function() private$..separator$value,
        factorScoresOV = function() private$..factorScoresOV$value),
    private = list(
        ..dep = NA,
        ..separator = NA,
        ..factorScoresOV = NA)
)

varsplitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "varsplitResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        factorScoresOV = function() private$.items[["factorScoresOV"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Split Column")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Split Column"))
            self$add(jmvcore::Output$new(
                options=options,
                name="factorScoresOV",
                title="New Columns",
                initInRun=TRUE))}))

varsplitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "varsplitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SplitColumn",
                name = "varsplit",
                version = c(1,0,0),
                options = options,
                results = varsplitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Split Column
#'
#' 
#' @param data .
#' @param dep .
#' @param separator .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$factorScoresOV} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
varsplit <- function(
    data,
    dep,
    separator = "comma") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("varsplit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- varsplitOptions$new(
        dep = dep,
        separator = separator)

    analysis <- varsplitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

